type: destination-policy
name: db-circuit
spec:
  destination: cloudant-service.default.svc.cluster.local
  policy:
    - circuitBreaker:
        simpleCb:
          maxConnections: 1
          httpMaxPendingRequests: 1
          httpConsecutiveErrors: 1
          sleepWindow: 15m
          httpDetectionInterval: 1s
          httpMaxEjectionPercent: 100
          #httpMaxRequests: 1
          #httpMaxRequestsPerConnection: 1
          
        
