apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-vote-sample
  labels:
    app: microprofile-app
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vote-deployment
        app: vote-deployment
        version: v1
    spec:
      containers:
      - name: microservice-vote
        #change this image name
        image: journeycode/microservice-ol-vote
        imagePullPolicy: IfNotPresent
        env:
        - name: dbUsername
          valueFrom:
            secretKeyRef:
              name: cloudant-secret
              key: dbUsername
        - name: dbPassword
          valueFrom:
            secretKeyRef:
              name: cloudant-secret
              key: dbPassword 
        - name: dbUrl
          value: http://cloudant-service:80
        ports:
          - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: microprofile-app
spec:
  ports:
    - port: 9080
      targetPort: 9080
      name: http
  selector:
    name: vote-deployment
